name: "TF Security Scan"

on:
  workflow_dispatch:
env:
  infra_env: "dev"
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    #environment: ${{ env.infra_env }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Set Env
      shell: bash
      working-directory: "terraform/${{ env.infra_env }}"
      run: cp *.tf ..\
        
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: ls -l && terraform init
      working-directory: "terraform"

    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@v1
      id: msdo
      with:
        categories: 'IaC'
        tools: 'terrascan'
